# Generated by Django 4.0.3 on 2022-04-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('$', 'US Dollars ($)')], max_length=5),
        ),
    ]
