# Generated by Django 4.0.3 on 2022-04-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale_management', '0002_alter_product_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='currency',
        ),
    ]
