# Generated by Django 4.0.3 on 2022-05-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_management', '0004_orderdetail_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Accepted'), (2, 'Rejected')], default=0),
        ),
    ]
