# Generated by Django 4.0.3 on 2022-05-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_management', '0005_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Accepted'), (0, 'New'), (2, 'Rejected')], default=0),
        ),
    ]
