# Generated by Django 4.0.3 on 2022-05-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_management', '0006_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliver_at',
            new_name='deliver_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='purchase_at',
            new_name='purchase_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Accepted')], default=0),
        ),
    ]
