# Generated by Django 4.0.3 on 2022-05-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_management', '0007_rename_deliver_at_order_deliver_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Accepted'), (0, 'New')], default=0),
        ),
    ]
